# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 16:03


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20140917_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformfield',
            name='transform',
        ),
        migrations.AlterField(
            model_name='transforminstance',
            name='transform',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Transform',
        ),
        migrations.DeleteModel(
            name='TransformField',
        ),
    ]
