# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_transforminstance_variable_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.TextField()),
                ('params', models.TextField(blank=True, null=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Store')),
            ],
        ),
    ]
