# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_variableinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='variableinstance',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
