# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_variableinstance_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiply', models.FloatField(default=1.0)),
                ('add', models.FloatField(default=0.0)),
                ('transform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TransformInstance')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.VariableInstance')),
            ],
        ),
    ]
