# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 20:11


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170408_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('duration_secs', models.IntegerField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Config')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Playlist')),
            ],
        ),
    ]
