# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_playlist_playlistconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistconfig',
            name='duration_secs',
        ),
        migrations.AddField(
            model_name='playlist',
            name='base_duration_secs',
            field=models.FloatField(default=30),
        ),
        migrations.AddField(
            model_name='playlistconfig',
            name='duration',
            field=models.FloatField(default=1.0),
        ),
    ]
