# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-01 23:10


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170720_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastPlayed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Playlist')),
            ],
        ),
    ]
