# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_lastplayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastplayed',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Playlist'),
        ),
    ]
